### ISSUE TITLE
Convert time parameter from YYYYMMDD to YYYY to perform wms requests

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/service-proxywms#24]
In the context of this project we need to convert the time parameter we use for the WMTS to YYYY to perform the WMS request in the background.

https://github.com/geoadmin/service-proxywms/blob/master/service_proxywms/main.py#L177

if time is current -> use it as is
if time is YYYYMMDD -> YYYY
if time is YYYYMM -> YYYY
if time is YYYY -> use it as is

Just change the time parameter in the WMS request.
https://github.com/geoadmin/service-proxywms/blob/master/service_proxywms/main.py#L45
Always keep the time parameter provided in the path when caching the tile.
https://github.com/geoadmin/service-proxywms/blob/master/service_proxywms/main.py#L209

**Comment by gjn** [comment]
Not really a fan. We will have data with sub-year resolution in the future. I would not translate the time parameter at all. But I would assure that public wmts timestamps are supported in the wms.

Keep it simple.

**Comment by loicgasser** [comment]
If you say so. I am not aware of such cases and I am not sure how you would handle that client side.
